### ISSUE TITLE
add Rail

### ISSUE THREAD

**Issue by Pantyhose-X** [ISs25u/codeblock#1]
Rail was built quickly

**Comment by gigaturbo** [comment]
> Rail was built quickly

Can you explain more please?

**Comment by Pantyhose-X** [comment]
> > Rail was built quickly
> 
> Can you explain more please?

add node block `carts:brakerali` `carts:powerrail` `carts:rail`

---
5.5.1 Unable to find codeblock mods in minetest client

**Comment by Pantyhose-X** [comment]
Roller coaster ride via Rail

**Comment by Pantyhose-X** [comment]
[Completed](https://github.com/gigaturbo/codeblock/pull/4)
