### ISSUE TITLE
.tr syntax error: unknown argument

### ISSUE THREAD

**Issue by rubenwardy** [ISs25u/codeblock#5]
`@1` isn't in the source string

https://github.com/gigaturbo/codeblock/blob/master/locale/codeblock.fr.tr#L52

**Comment by gigaturbo** [comment]
Fixed in [7fd5f64](https://github.com/gigaturbo/codeblock/commit/7fd5f6437da5c074d0ed7cdac0783113a4f9d7fd)
Thanks !
